### PR TITLE
Manager dashboard

### PR DESCRIPTION
**Pull request by str1nker**
1) React component ManagerDashboard  with menu list and tables of users.
2) Functions invite one, invite many from csv file, kick has been realized.
3) Treatment errors with multicolored alerts, that are available like a one component.
4) Manager send mails to students for invite it, on mail include unique token.
This token allows students confirm their account and join to foundation.
5) Rspec tests for controller manager_dashboard and InviteMailer.
6) Change association concept between models foundation and user.

### CODE REVIEW

**Comment by str1nker** [comment]
> Good job, but add csv files to gitignore.
They need for tests, so people, who load project can't  run they. Or on tests i can makes new files and delete them  everytime?

**Comment by PFdev6** [comment]
@str1nker You can add examples csv files in README.

**Comment by str1nker** [comment]
@PFdev6   I'll do something with it)

**Comment by PFdev6** [comment]
Perfect

**Pull request merged**
